version: "3.9"
services:
  mpie-framework-starter:
    build: .
    volumes:
      - .:/www
    ports:
      - "8989:8989"
    networks:
      - docker-net
    links:
      - redis

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  phpredisadmin:
    image: "erikdubbelboer/phpredisadmin"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    links:
      - redis
    ports:
      - "8080:80"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - docker-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - docker-net
    restart: unless-stopped

networks:
  docker-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  cache:
    driver: local